export default [
  { letter: 'а' },
  { letter: 'б' },
  { letter: 'в', variants: ['v'], active: true },
  { letter: 'г' },
  { letter: 'д' },
  { letter: 'е', variants: ['є', 'э' /* ять */ ] },
  { letter: 'ж' },
  { letter: 'з', variants: ['ѕ'] },
  { letter: 'и', variants: ['і', 'm' /* ижица с двойным графисом */ ] },
  { letter: 'к', etc: 'x' /* кси */ },
  { letter: 'л' },
  { letter: 'м' },
  { letter: 'н' },
  { letter: 'о', variants: ['o', 'w', 'q' /* оле */ ], etc: 't' /* от */ },
  { letter: 'п', etc: 'p' /* пси */ },
  { letter: 'р' },
  { letter: 'с' },
  { letter: 'т' },
  { letter: 'u', variants: ['у'] },
  { letter: 'ф', variants: ['f'] },
  { letter: 'х' },
  { letter: 'ц' },
  { letter: 'ч' },
  { letter: 'ш' },
  { letter: 'щ' },
  { letter: 'ю' },
  { letter: 'z', variants: ['я'] },
];
